from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('login-visitor/', login_visitor),
    path('register-visitor/', register_visitor),
    path('browse-visited-museums/', browse_visited_museums),
    path('login-supervisor-employee/', login_supervisor_employee),
    path('register-supervisor/', register_supervisor),
    path('get-supervisor-employees/', get_supervisor_employees),
    path('get-supervisor-info/', get_supervisor_info),
    path('register-employee/', register_employee),
    path('update-employee/', update_employee),
    path('delete-employee/', delete_employee),
    path("get-artifacts/", get_artifacts),
    path("add-artifact/", add_artifact),
    path("update-artifact/", update_artifact),
    path("delete-artifact/", delete_artifact),
    path("add-exhibit/", add_exhibit),
    path("update-exhibit/", update_exhibit),
    path("delete-exhibit/", delete_exhibit),
    path("get-exhibits/", get_exhibits),
    path("get-events/", get_events),
    path("add-event/", add_event),
    path("update-event/", update_event),
    path("delete-event/", delete_event),
    path("get-artists/", get_artists),
    path("add-artist/", add_artist),
    path("update-artist/", update_artist),
    path("delete-artist/", delete_artist),
    path("get-artifacts-for-artist/", get_artifacts_for_artist),
    path("get-employee-info/", get_employee_info),
    path("record-edit-artifact/", record_edit_artifact),
    path("record-edit-event/", record_edit_event),
    path("record-edit-exhibit/", record_edit_exhibit),
    path("get-edit-logs/", get_edit_logs),

    path("get-all-artifacts/", get_all_artifacts),
    path("get-all-events/", get_all_events),
    path("get-all-exhibits/", get_all_exhibits),
    path("get-all-museums/", get_all_museums),
    path("get-all-visitors/", get_all_visitors),
    path("get-visited-museums/", get_visited_museums),
    path("add-visited-museum/", add_visited_museum),
    path("delete-visited-museum/", delete_visited_museum),
    path("submit-artifact-review/", submit_artifact_review),
    path("delete-artifact-review/", delete_artifact_review),
    path('get-visitor-artifact-reviews/', get_visitor_artifact_reviews),
    path("get-artifact-reviews/", get_artifact_reviews),
    path("submit-event-review/", submit_event_review),
    path("get-event-reviews/", get_event_reviews),

    path('get-visitor-event-reviews/', get_visitor_event_reviews),

    # JWT auth endpoints
    path('token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', CustomTokenObtainPairView.as_view(), name='token_refresh'),
]